version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - DB_URL=mongodb://database/SmartSpace
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  database-data:
